apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomize
namePrefix: kustomize-
commonLabels:
  app: nginx
  namespace: kustomize
resources:
  - deployment.yaml
  - service.yaml
# configMapGenerator:
# - name: my-application-properties
#   files:
#   - application.properties